### ISSUE TITLE
代码无法运行

### ISSUE THREAD

**Issue by weiwuxian1998** [MihawkHu/DCASE2020_task1#11]
作者你好，我在尝试运行train_mobnet.py时，发生错误。以下是报错信息
Traceback (most recent call last):
  File "D:/weiwuxian/task1b/train/train_mobnet.py", line 15, in <module>
    from mobnet import model_mobnet
  File "D:\weiwuxian\task1b\train\mobnet.py", line 150, in <module>
    model.load_weights("")
  File "E:\anaconda\envs\task1b\lib\site-packages\keras\engine\network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "E:\anaconda\envs\task1b\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "E:\anaconda\envs\task1b\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
ValueError: Invalid file name (invalid file name)
请问这个有什么解决办法吗，感谢

**Comment by huckiyang** [comment]
Hello @weiwuxian1998 

Please `git pull` the just updated new code repo and try to run again or consider switching to a Linux environment.   

Noted this tensorflow and keras implementation is only supported in the Linux environment since the Windows environment is often unstable and varied. It looks there was a file name issue in the environment or your `h5py` setup is with some issue.
