### ISSUE TITLE
想问下代码中的特征文件是怎么生成的呢？

### ISSUE THREAD

**Issue by wangdong2222** [MihawkHu/DCASE2020_task1#15]
hi 您好，我运行python3 train_mobnet.py  报以下错误
Traceback (most recent call last):
  File "train_mobnet.py", line 49, in <module>
    data_val, y_val = load_data_2020(feat_path, val_csv, num_freq_bin, 'logmel')
  File "../utils.py", line 27, in load_data_2020
    with open(filepath,'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'features/logmel128_scaled_d_dd//street_pedestrian-lyon-1162-44093-a.logmel'

想问下代码中的feat_path指的是什么，要如何生成呢

期待您的回复，谢谢

**Comment by wangdong2222** [comment]
看了下代码，知道了，需要先运行extr_feat_2020.py
