### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by EmreOzkose** [MihawkHu/DCASE2020_task1#20]
Hi, thank you for great work and sharing code. I create environment with `DCASE2020_task1/task1a/environment.yml`. Then I try to extract features and I got this error.

```
(d20-keras) yunusemre.ozkose@server:/path/to/DCASE2020_task1/task1a/10class$ python extr_feat_2020_nodelta_scaled.py 
Traceback (most recent call last):
  File "extr_feat_2020_nodelta_scaled.py", line 37, in <module>
    logmel_data[:,:,0]= librosa.feature.melspectrogram(stereo[:], sr=sr, n_fft=num_fft, hop_length=hop_length, n_mels=num_freq_bin, fmin=0.0, fmax=sr/2, htk=True, norm=None)
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/librosa/feature/spectral.py", line 1531, in melspectrogram
    power=power)
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/librosa/core/spectrum.py", line 1557, in _spectrogram
    S = np.abs(stft(y, n_fft=n_fft, hop_length=hop_length))**power
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/librosa/core/spectrum.py", line 161, in stft
    util.valid_audio(y)
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/librosa/util/utils.py", line 163, in valid_audio
    'ndim={:d}, shape={}'.format(y.ndim, y.shape))
librosa.util.exceptions.ParameterError: Invalid shape for monophonic audio: ndim=2, shape=(441000, 2)
```

Since audios are stereo, soundfile cannot handle this. How can achieve this? I think one solution might be 

change this line:
```
logmel_data[:,:,0]= librosa.feature.melspectrogram(stereo[:], sr=sr, n_fft=num_fft, hop_length=hop_length, n_mels=num_freq_bin, fmin=0.0, fmax=sr/2, htk=True, norm=None)
```
to
```
logmel_data[:,:,0]= librosa.feature.melspectrogram(stereo[:, 0], sr=sr, n_fft=num_fft, hop_length=hop_length, n_mels=num_freq_bin, fmin=0.0, fmax=sr/2, htk=True, norm=None)
logmel_data[:,:,1]= librosa.feature.melspectrogram(stereo[:, 1], sr=sr, n_fft=num_fft, hop_length=hop_length, n_mels=num_freq_bin, fmin=0.0, fmax=sr/2, htk=True, norm=None)
```

Of course we also have to change `num_channel = 2`.

Do you think that it will change distribution of the features ? I think features will be affected, because of normalization?

**Comment by EmreOzkose** [comment]
It raises an error when I run `eval_singlemodel`: 

```
Traceback (most recent call last):
  File "eval_singlemodel_10class.py", line 67, in <module>
    preds = best_model.predict(data_val)
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/path/to/miniconda3/envs/d20-keras/lib/python3.6/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (128, None, 3) but got array with shape (128, 423, 6)
```

Then I tried:
```
logmel_data[:,:,0]= librosa.feature.melspectrogram(stereo[0] / 2 + stereo[1] / 2, sr=sr, n_fft=num_fft, hop_length=hop_length, n_mels=num_freq_bin, fmin=0.0, fmax=sr/2, htk=True, norm=None)
```

and I got 0.1 accuracy.

**Comment by EmreOzkose** [comment]
I re-downloaded data and it works fine. Data might be broken or something else.
